### ISSUE TITLE
Error in gen_Onet_train_data.py

### ISSUE THREAD

**Issue by macsermkiat** [kuaikuaikim/DFace#10]
It gave error from negative dimension, I try to find the value and it's -1, not sure where it came from

> ~/DFace/dface/core/detect.py in detect_rnet(self, im, dets)
>     389         for i in range(num_boxes):
> --> 390             tmp = np.zeros((tmph[i], tmpw[i], 3), dtype=np.uint8)
>     391             tmp[dy[i]:edy[i]+1, dx[i]:edx[i]+1, :] = im[y[i]:ey[i]+1, x[i]:ex[i]+1, :]
>     392             crop_im = cv2.resize(tmp, (24, 24))
> 
> ValueError: negative dimensions are not allowed

**Comment by kuaikuaikim** [comment]
@macsermkiat which value is -1, can you show me more details, thanks.

**Comment by kimimatias** [comment]
Hello. I got the same error. It came from 390 line of /DFace/dface/core/detect.py. Namely after the first hundred processed images in `tmp = np.zeros(tmph[i], tmpw[i], 3), dtype=np.uint8)` tmph[i] == -4 and tmpw[i] == -4 when i == 457

**Comment by kuaikuaikim** [comment]
@kimimatias which version of your python

**Comment by macsermkiat** [comment]
@kuaikuaikim I'm using Python 2.7
It's as @kimimatias wrote. There're some of tmph[i] < 0
There are also sometimes tmph[i] == 0 too, that also caused error.

**Comment by kuaikuaikim** [comment]
@macsermkiat @kimimatias 
Maybe some bias sample make this problem,  try filter this sample image of  negative prediction.

**Comment by kimimatias** [comment]
@kuaikuaikim I'm using Python 3.5

**Comment by kimimatias** [comment]
@kuaikuaikim I'm using Python 3.5
